name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
            build: true
          - os: ubuntu-24.04-arm
            arch: arm64
            build: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install golang make
      - name: Run go test
        run: go test -v .
